//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDCplusLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDCplusLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure loading configuration..
        /// </summary>
        internal static string exFailureLoadingConfiguration {
            get {
                return ResourceManager.GetString("exFailureLoadingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure updating tab control..
        /// </summary>
        internal static string exFailureUpdatingTabs {
            get {
                return ResourceManager.GetString("exFailureUpdatingTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACL.
        /// </summary>
        internal static string lblAcl {
            get {
                return ResourceManager.GetString("lblAcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACL entries.
        /// </summary>
        internal static string lblAclEntries {
            get {
                return ResourceManager.GetString("lblAclEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblAclName {
            get {
                return ResourceManager.GetString("lblAclName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add column.
        /// </summary>
        internal static string lblAddColumn {
            get {
                return ResourceManager.GetString("lblAddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add column configuration.
        /// </summary>
        internal static string lblAddConfig {
            get {
                return ResourceManager.GetString("lblAddConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add operator.
        /// </summary>
        internal static string lblAddOperator {
            get {
                return ResourceManager.GetString("lblAddOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add term.
        /// </summary>
        internal static string lblAddTerm {
            get {
                return ResourceManager.GetString("lblAddTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANY.
        /// </summary>
        internal static string lblAny {
            get {
                return ResourceManager.GetString("lblAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply column configuration.
        /// </summary>
        internal static string lblApplyConfig {
            get {
                return ResourceManager.GetString("lblApplyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available columns.
        /// </summary>
        internal static string lblAvailableColumns {
            get {
                return ResourceManager.GetString("lblAvailableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available column configurations.
        /// </summary>
        internal static string lblAvailableConfig {
            get {
                return ResourceManager.GetString("lblAvailableConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string lblBytes {
            get {
                return ResourceManager.GetString("lblBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string lblCancel {
            get {
                return ResourceManager.GetString("lblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDCplus.
        /// </summary>
        internal static string lblCDCplusMainWindow {
            get {
                return ResourceManager.GetString("lblCDCplusMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed flags.
        /// </summary>
        internal static string lblChangedFlags {
            get {
                return ResourceManager.GetString("lblChangedFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in.
        /// </summary>
        internal static string lblCheckin {
            get {
                return ResourceManager.GetString("lblCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in from checkout path.
        /// </summary>
        internal static string lblCheckinFromCheckoutPath {
            get {
                return ResourceManager.GetString("lblCheckinFromCheckoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in from other file.
        /// </summary>
        internal static string lblCheckinFromOtherFile {
            get {
                return ResourceManager.GetString("lblCheckinFromOtherFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        internal static string lblChildren {
            get {
                return ResourceManager.GetString("lblChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose target object.
        /// </summary>
        internal static string lblChooseTarget {
            get {
                return ResourceManager.GetString("lblChooseTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose target objects.
        /// </summary>
        internal static string lblChooseTargets {
            get {
                return ResourceManager.GetString("lblChooseTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move column down.
        /// </summary>
        internal static string lblColumnDown {
            get {
                return ResourceManager.GetString("lblColumnDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move column up.
        /// </summary>
        internal static string lblColumnUp {
            get {
                return ResourceManager.GetString("lblColumnUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width preview.
        /// </summary>
        internal static string lblColumnWidthPreview {
            get {
                return ResourceManager.GetString("lblColumnWidthPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common permissions.
        /// </summary>
        internal static string lblCommonPermissions {
            get {
                return ResourceManager.GetString("lblCommonPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column configuration name.
        /// </summary>
        internal static string lblConfigName {
            get {
                return ResourceManager.GetString("lblConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string lblContains {
            get {
                return ResourceManager.GetString("lblContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblContentChanged {
            get {
                return ResourceManager.GetString("lblContentChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string lblCount {
            get {
                return ResourceManager.GetString("lblCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        internal static string lblCreatedBy {
            get {
                return ResourceManager.GetString("lblCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new version.
        /// </summary>
        internal static string lblCreateNewVersion {
            get {
                return ResourceManager.GetString("lblCreateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation date / time.
        /// </summary>
        internal static string lblCreationDate {
            get {
                return ResourceManager.GetString("lblCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current permissions.
        /// </summary>
        internal static string lblCurrentPermissions {
            get {
                return ResourceManager.GetString("lblCurrentPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all versions.
        /// </summary>
        internal static string lblDeleteAllVersions {
            get {
                return ResourceManager.GetString("lblDeleteAllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete column configuration.
        /// </summary>
        internal static string lblDeleteConfig {
            get {
                return ResourceManager.GetString("lblDeleteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete protected relations.
        /// </summary>
        internal static string lblDeleteProtectedRelations {
            get {
                return ResourceManager.GetString("lblDeleteProtectedRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected versions.
        /// </summary>
        internal static string lblDeleteSelectedVersions {
            get {
                return ResourceManager.GetString("lblDeleteSelectedVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit import settings.
        /// </summary>
        internal static string lblEditFileImportRequests {
            get {
                return ResourceManager.GetString("lblEditFileImportRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit content.
        /// </summary>
        internal static string lblEditSelectedNodeContent {
            get {
                return ResourceManager.GetString("lblEditSelectedNodeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit selected node(s) parameters.
        /// </summary>
        internal static string lblEditSelectedNodeParas {
            get {
                return ResourceManager.GetString("lblEditSelectedNodeParas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic configuration.
        /// </summary>
        internal static string lblEmergencyConfig {
            get {
                return ResourceManager.GetString("lblEmergencyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder with all contents.
        /// </summary>
        internal static string lblEntireFolder {
            get {
                return ResourceManager.GetString("lblEntireFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equals.
        /// </summary>
        internal static string lblEquals {
            get {
                return ResourceManager.GetString("lblEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string lblFalse {
            get {
                return ResourceManager.GetString("lblFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field name.
        /// </summary>
        internal static string lblFieldName {
            get {
                return ResourceManager.GetString("lblFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string lblFilename {
            get {
                return ResourceManager.GetString("lblFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        internal static string lblFiles {
            get {
                return ResourceManager.GetString("lblFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed version.
        /// </summary>
        internal static string lblFixedVersion {
            get {
                return ResourceManager.GetString("lblFixedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string lblFolder {
            get {
                return ResourceManager.GetString("lblFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder Id.
        /// </summary>
        internal static string lblFolderId {
            get {
                return ResourceManager.GetString("lblFolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path.
        /// </summary>
        internal static string lblFolderPath {
            get {
                return ResourceManager.GetString("lblFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder permissions.
        /// </summary>
        internal static string lblFolderPermissions {
            get {
                return ResourceManager.GetString("lblFolderPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder type.
        /// </summary>
        internal static string lblFolderType {
            get {
                return ResourceManager.GetString("lblFolderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        internal static string lblFormat {
            get {
                return ResourceManager.GetString("lblFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than.
        /// </summary>
        internal static string lblGreaterThan {
            get {
                return ResourceManager.GetString("lblGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than or equal.
        /// </summary>
        internal static string lblGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("lblGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string lblGroup {
            get {
                return ResourceManager.GetString("lblGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide settings.
        /// </summary>
        internal static string lblHideSettings {
            get {
                return ResourceManager.GetString("lblHideSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide translations.
        /// </summary>
        internal static string lblHideTranslations {
            get {
                return ResourceManager.GetString("lblHideTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string lblId {
            get {
                return ResourceManager.GetString("lblId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string lblImport {
            get {
                return ResourceManager.GetString("lblImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import ....
        /// </summary>
        internal static string lblImportDots {
            get {
                return ResourceManager.GetString("lblImportDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version.
        /// </summary>
        internal static string lblLatestVersion {
            get {
                return ResourceManager.GetString("lblLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than.
        /// </summary>
        internal static string lblLessThan {
            get {
                return ResourceManager.GetString("lblLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than or equal.
        /// </summary>
        internal static string lblLessThanOrEqual {
            get {
                return ResourceManager.GetString("lblLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifecycle.
        /// </summary>
        internal static string lblLifecycle {
            get {
                return ResourceManager.GetString("lblLifecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifecycle and state.
        /// </summary>
        internal static string lblLifecycleAndState {
            get {
                return ResourceManager.GetString("lblLifecycleAndState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifecycle state.
        /// </summary>
        internal static string lblLifecycleState {
            get {
                return ResourceManager.GetString("lblLifecycleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link permissions.
        /// </summary>
        internal static string lblLinkPermissions {
            get {
                return ResourceManager.GetString("lblLinkPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked by.
        /// </summary>
        internal static string lblLockedBy {
            get {
                return ResourceManager.GetString("lblLockedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string lblMessage {
            get {
                return ResourceManager.GetString("lblMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string lblMetadataChanged {
            get {
                return ResourceManager.GetString("lblMetadataChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification date / time.
        /// </summary>
        internal static string lblModificationDate {
            get {
                return ResourceManager.GetString("lblModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified by.
        /// </summary>
        internal static string lblModifiedBy {
            get {
                return ResourceManager.GetString("lblModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named configuration: {0}.
        /// </summary>
        internal static string lblNamedConfig {
            get {
                return ResourceManager.GetString("lblNamedConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string lblNewFolder {
            get {
                return ResourceManager.GetString("lblNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        internal static string lblNewName {
            get {
                return ResourceManager.GetString("lblNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object without content.
        /// </summary>
        internal static string lblNewObjectWithoutContent {
            get {
                return ResourceManager.GetString("lblNewObjectWithoutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lblNo {
            get {
                return ResourceManager.GetString("lblNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No format.
        /// </summary>
        internal static string lblNoFormat {
            get {
                return ResourceManager.GetString("lblNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lifecycle.
        /// </summary>
        internal static string lblNoLifecycle {
            get {
                return ResourceManager.GetString("lblNoLifecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT.
        /// </summary>
        internal static string lblNot {
            get {
                return ResourceManager.GetString("lblNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string lblNotification {
            get {
                return ResourceManager.GetString("lblNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name.
        /// </summary>
        internal static string lblObjectName {
            get {
                return ResourceManager.GetString("lblObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object permissions.
        /// </summary>
        internal static string lblObjectPermissions {
            get {
                return ResourceManager.GetString("lblObjectPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type.
        /// </summary>
        internal static string lblObjectType {
            get {
                return ResourceManager.GetString("lblObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string lblOk {
            get {
                return ResourceManager.GetString("lblOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string lblOwner {
            get {
                return ResourceManager.GetString("lblOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent id.
        /// </summary>
        internal static string lblParentFolderId {
            get {
                return ResourceManager.GetString("lblParentFolderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parents.
        /// </summary>
        internal static string lblParents {
            get {
                return ResourceManager.GetString("lblParents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string lblPath {
            get {
                return ResourceManager.GetString("lblPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string lblPermissions {
            get {
                return ResourceManager.GetString("lblPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string lblProperties {
            get {
                return ResourceManager.GetString("lblProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string lblQuery {
            get {
                return ResourceManager.GetString("lblQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata (raw).
        /// </summary>
        internal static string lblRawMetadata {
            get {
                return ResourceManager.GetString("lblRawMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relates to.
        /// </summary>
        internal static string lblRelatesTo {
            get {
                return ResourceManager.GetString("lblRelatesTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation permissions.
        /// </summary>
        internal static string lblRelationPermissions {
            get {
                return ResourceManager.GetString("lblRelationPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations.
        /// </summary>
        internal static string lblRelations {
            get {
                return ResourceManager.GetString("lblRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation type.
        /// </summary>
        internal static string lblRelationType {
            get {
                return ResourceManager.GetString("lblRelationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string lblReload {
            get {
                return ResourceManager.GetString("lblReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove column.
        /// </summary>
        internal static string lblRemoveColumn {
            get {
                return ResourceManager.GetString("lblRemoveColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversed sort order.
        /// </summary>
        internal static string lblReverse {
            get {
                return ResourceManager.GetString("lblReverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Id.
        /// </summary>
        internal static string lblRootId {
            get {
                return ResourceManager.GetString("lblRootId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lblSave {
            get {
                return ResourceManager.GetString("lblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save column configuration.
        /// </summary>
        internal static string lblSaveConfig {
            get {
                return ResourceManager.GetString("lblSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string lblSearchEditor {
            get {
                return ResourceManager.GetString("lblSearchEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search folders.
        /// </summary>
        internal static string lblSearchFolders {
            get {
                return ResourceManager.GetString("lblSearchFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search objects.
        /// </summary>
        internal static string lblSearchObjects {
            get {
                return ResourceManager.GetString("lblSearchObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        internal static string lblSearchResults {
            get {
                return ResourceManager.GetString("lblSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select relation type.
        /// </summary>
        internal static string lblSelectRelationType {
            get {
                return ResourceManager.GetString("lblSelectRelationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set column configuration as default.
        /// </summary>
        internal static string lblSetConfigAsDefault {
            get {
                return ResourceManager.GetString("lblSetConfigAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All versions.
        /// </summary>
        internal static string lblShowAllVersions {
            get {
                return ResourceManager.GetString("lblShowAllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest versions (branches).
        /// </summary>
        internal static string lblShowLatestInBranches {
            get {
                return ResourceManager.GetString("lblShowLatestInBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version (trunk).
        /// </summary>
        internal static string lblShowLatestInHead {
            get {
                return ResourceManager.GetString("lblShowLatestInHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shown columns.
        /// </summary>
        internal static string lblShownColumns {
            get {
                return ResourceManager.GetString("lblShownColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show query.
        /// </summary>
        internal static string lblShowQuery {
            get {
                return ResourceManager.GetString("lblShowQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show settings.
        /// </summary>
        internal static string lblShowSettings {
            get {
                return ResourceManager.GetString("lblShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show translations.
        /// </summary>
        internal static string lblShowTranslations {
            get {
                return ResourceManager.GetString("lblShowTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string lblSize {
            get {
                return ResourceManager.GetString("lblSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by this column.
        /// </summary>
        internal static string lblSortThisColumn {
            get {
                return ResourceManager.GetString("lblSortThisColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard configuration.
        /// </summary>
        internal static string lblStandardConfig {
            get {
                return ResourceManager.GetString("lblStandardConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starts with.
        /// </summary>
        internal static string lblStartsWith {
            get {
                return ResourceManager.GetString("lblStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superuser.
        /// </summary>
        internal static string lblSuperuser {
            get {
                return ResourceManager.GetString("lblSuperuser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target folder.
        /// </summary>
        internal static string lblTargetFolder {
            get {
                return ResourceManager.GetString("lblTargetFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total size.
        /// </summary>
        internal static string lblTotalSize {
            get {
                return ResourceManager.GetString("lblTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translations - Source language: {0}.
        /// </summary>
        internal static string lblTranslationsTitle {
            get {
                return ResourceManager.GetString("lblTranslationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblTreeContent {
            get {
                return ResourceManager.GetString("lblTreeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My documents.
        /// </summary>
        internal static string lblTreeHome {
            get {
                return ResourceManager.GetString("lblTreeHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked objects.
        /// </summary>
        internal static string lblTreeLocked {
            get {
                return ResourceManager.GetString("lblTreeLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string lblTreeResults {
            get {
                return ResourceManager.GetString("lblTreeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Searches.
        /// </summary>
        internal static string lblTreeSearches {
            get {
                return ResourceManager.GetString("lblTreeSearches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks and notifications.
        /// </summary>
        internal static string lblTreeTasks {
            get {
                return ResourceManager.GetString("lblTreeTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string lblTrue {
            get {
                return ResourceManager.GetString("lblTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object type.
        /// </summary>
        internal static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved changes.
        /// </summary>
        internal static string lblUnsavedChanges {
            get {
                return ResourceManager.GetString("lblUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update child references to latest version in head.
        /// </summary>
        internal static string lblUpdateToLatestInHead {
            get {
                return ResourceManager.GetString("lblUpdateToLatestInHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable (specify name).
        /// </summary>
        internal static string lblVariableSpecifyName {
            get {
                return ResourceManager.GetString("lblVariableSpecifyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string lblVersion {
            get {
                return ResourceManager.GetString("lblVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select version.
        /// </summary>
        internal static string lblVersionSelector {
            get {
                return ResourceManager.GetString("lblVersionSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string lblViewDetails {
            get {
                return ResourceManager.GetString("lblViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large icons.
        /// </summary>
        internal static string lblViewLargeIcons {
            get {
                return ResourceManager.GetString("lblViewLargeIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small icons.
        /// </summary>
        internal static string lblViewSmallIcons {
            get {
                return ResourceManager.GetString("lblViewSmallIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column width.
        /// </summary>
        internal static string lblWidth {
            get {
                return ResourceManager.GetString("lblWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lblYes {
            get {
                return ResourceManager.GetString("lblYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add metaset.
        /// </summary>
        internal static string mnuAddMetaset {
            get {
                return ResourceManager.GetString("mnuAddMetaset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add metaset type.
        /// </summary>
        internal static string mnuAddMetasetType {
            get {
                return ResourceManager.GetString("mnuAddMetasetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new relation.
        /// </summary>
        internal static string mnuAddNewRelation {
            get {
                return ResourceManager.GetString("mnuAddNewRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append content from file.
        /// </summary>
        internal static string mnuAppendContent {
            get {
                return ResourceManager.GetString("mnuAppendContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel checkout.
        /// </summary>
        internal static string mnuCancelCheckout {
            get {
                return ResourceManager.GetString("mnuCancelCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in.
        /// </summary>
        internal static string mnuCheckin {
            get {
                return ResourceManager.GetString("mnuCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out.
        /// </summary>
        internal static string mnuCheckout {
            get {
                return ResourceManager.GetString("mnuCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        internal static string mnuClone {
            get {
                return ResourceManager.GetString("mnuClone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string mnuCopy {
            get {
                return ResourceManager.GetString("mnuCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy filename.
        /// </summary>
        internal static string mnuCopyFilename {
            get {
                return ResourceManager.GetString("mnuCopyFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy path and filename.
        /// </summary>
        internal static string mnuCopyPathFilename {
            get {
                return ResourceManager.GetString("mnuCopyPathFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy ticket.
        /// </summary>
        internal static string mnuCopyTicket {
            get {
                return ResourceManager.GetString("mnuCopyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new version.
        /// </summary>
        internal static string mnuCreateNewVersion {
            get {
                return ResourceManager.GetString("mnuCreateNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object without content.
        /// </summary>
        internal static string mnuCreateObjectWithoutContent {
            get {
                return ResourceManager.GetString("mnuCreateObjectWithoutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string mnuCut {
            get {
                return ResourceManager.GetString("mnuCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete links.
        /// </summary>
        internal static string mnuDeleteLinks {
            get {
                return ResourceManager.GetString("mnuDeleteLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete metaset.
        /// </summary>
        internal static string mnuDeleteMetaset {
            get {
                return ResourceManager.GetString("mnuDeleteMetaset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete metaset type.
        /// </summary>
        internal static string mnuDeleteMetasetType {
            get {
                return ResourceManager.GetString("mnuDeleteMetasetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string mnuExport {
            get {
                return ResourceManager.GetString("mnuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import rendition.
        /// </summary>
        internal static string mnuImportRendition {
            get {
                return ResourceManager.GetString("mnuImportRendition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to folder.
        /// </summary>
        internal static string mnuLinkToFolder {
            get {
                return ResourceManager.GetString("mnuLinkToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New folder.
        /// </summary>
        internal static string mnuNewFolder {
            get {
                return ResourceManager.GetString("mnuNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object from template.
        /// </summary>
        internal static string mnuNewObjectFromTemplate {
            get {
                return ResourceManager.GetString("mnuNewObjectFromTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New object without content.
        /// </summary>
        internal static string mnuNewObjectWithoutContent {
            get {
                return ResourceManager.GetString("mnuNewObjectWithoutContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open checked out file.
        /// </summary>
        internal static string mnuOpenCheckedOutFile {
            get {
                return ResourceManager.GetString("mnuOpenCheckedOutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new window.
        /// </summary>
        internal static string mnuOpenInNewWindow {
            get {
                return ResourceManager.GetString("mnuOpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste ....
        /// </summary>
        internal static string mnuPaste {
            get {
                return ResourceManager.GetString("mnuPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All versions.
        /// </summary>
        internal static string mnuPasteAllVersions {
            get {
                return ResourceManager.GetString("mnuPasteAllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected versions only.
        /// </summary>
        internal static string mnuPasteSelectedVersions {
            get {
                return ResourceManager.GetString("mnuPasteSelectedVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string mnuRemoveRelation {
            get {
                return ResourceManager.GetString("mnuRemoveRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename folder.
        /// </summary>
        internal static string mnuRenameFolder {
            get {
                return ResourceManager.GetString("mnuRenameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string mnuReplaceRelation {
            get {
                return ResourceManager.GetString("mnuReplaceRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select version of linked object.
        /// </summary>
        internal static string mnuSelectLinkVersion {
            get {
                return ResourceManager.GetString("mnuSelectLinkVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update to latest version.
        /// </summary>
        internal static string mnuUpdateRelation {
            get {
                return ResourceManager.GetString("mnuUpdateRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string mnuView {
            get {
                return ResourceManager.GetString("mnuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure versioning object. Versioning would have created a branch version, but branching is disabled in the current session..
        /// </summary>
        internal static string msgBranchingForbidden {
            get {
                return ResourceManager.GetString("msgBranchingForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you cancel the checkout, all changes are lost. Are you sure?.
        /// </summary>
        internal static string msgCancelCheckoutChangesLost {
            get {
                return ResourceManager.GetString("msgCancelCheckoutChangesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to open the checked out file in the associated application?.
        /// </summary>
        internal static string msgCheckoutOpenInAssociatedApp {
            get {
                return ResourceManager.GetString("msgCheckoutOpenInAssociatedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying folders from root is not supported..
        /// </summary>
        internal static string msgCopyingRootFoldersNotSupported {
            get {
                return ResourceManager.GetString("msgCopyingRootFoldersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying selected versions does not support folders..
        /// </summary>
        internal static string msgCopySelectedNoFoldersPermitted {
            get {
                return ResourceManager.GetString("msgCopySelectedNoFoldersPermitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty search definition..
        /// </summary>
        internal static string msgEmptySearchDefinition {
            get {
                return ResourceManager.GetString("msgEmptySearchDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure appending content from file..
        /// </summary>
        internal static string msgFailureAppendingContent {
            get {
                return ResourceManager.GetString("msgFailureAppendingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure applying properties to {0} objects..
        /// </summary>
        internal static string msgFailureApplyingProperties {
            get {
                return ResourceManager.GetString("msgFailureApplyingProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure checking in.
        /// </summary>
        internal static string msgFailureCheckingIn {
            get {
                return ResourceManager.GetString("msgFailureCheckingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred copying the selection..
        /// </summary>
        internal static string msgFailureCopying {
            get {
                return ResourceManager.GetString("msgFailureCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure copying to clipboard..
        /// </summary>
        internal static string msgFailureCopyingToClipboard {
            get {
                return ResourceManager.GetString("msgFailureCopyingToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure copying to clipboard. The selected reference was not found..
        /// </summary>
        internal static string msgFailureCopyingToClipboardNoChildFound {
            get {
                return ResourceManager.GetString("msgFailureCopyingToClipboardNoChildFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure creating object..
        /// </summary>
        internal static string msgFailureCreatingObject {
            get {
                return ResourceManager.GetString("msgFailureCreatingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of the following references failed..
        /// </summary>
        internal static string msgFailureCreatingReferences {
            get {
                return ResourceManager.GetString("msgFailureCreatingReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure deleting the selection, {0} item(s) were not deleted..
        /// </summary>
        internal static string msgFailureDeleting {
            get {
                return ResourceManager.GetString("msgFailureDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure completing delete operation due to insufficient permissions..
        /// </summary>
        internal static string msgFailureDeletingInsufPerm {
            get {
                return ResourceManager.GetString("msgFailureDeletingInsufPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure deleting object. Objects with successor versions can&apos;t be deleted..
        /// </summary>
        internal static string msgFailureDeletingVersionWithSuccessor {
            get {
                return ResourceManager.GetString("msgFailureDeletingVersionWithSuccessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure locking object, it is locked by another user..
        /// </summary>
        internal static string msgFailureLockingLockedByOtherUser {
            get {
                return ResourceManager.GetString("msgFailureLockingLockedByOtherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred moving the selection..
        /// </summary>
        internal static string msgFailureMoving {
            get {
                return ResourceManager.GetString("msgFailureMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure viewing the object..
        /// </summary>
        internal static string msgFailureViewingObject {
            get {
                return ResourceManager.GetString("msgFailureViewingObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure writing metadata.
        /// </summary>
        internal static string msgFailureWritingMetadata {
            get {
                return ResourceManager.GetString("msgFailureWritingMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors analysing the files. See the ToolTips of the files for details..
        /// </summary>
        internal static string msgImportErrorsReadToolTips {
            get {
                return ResourceManager.GetString("msgImportErrorsReadToolTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your permissions are not sufficient for the selected function..
        /// </summary>
        internal static string msgInsufficientPermissions {
            get {
                return ResourceManager.GetString("msgInsufficientPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the permission to add at least one of the relations..
        /// </summary>
        internal static string msgInsufficientPermissionsAddRelation {
            get {
                return ResourceManager.GetString("msgInsufficientPermissionsAddRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the permission to remove at least one of the relations..
        /// </summary>
        internal static string msgInsufficientPermissionsRemoveRelation {
            get {
                return ResourceManager.GetString("msgInsufficientPermissionsRemoveRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search returned many results ({0}). 
        ///Searching for all results can take several minutes. 
        ///Consider narrowing the search criteria.
        ///Do you want to show all results?.
        /// </summary>
        internal static string msgMoreThanXResults {
            get {
                return ResourceManager.GetString("msgMoreThanXResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the permission to create folders in the target folder..
        /// </summary>
        internal static string msgNoCreateFolderPermission {
            get {
                return ResourceManager.GetString("msgNoCreateFolderPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this repository, no lifecycles are defined..
        /// </summary>
        internal static string msgNoLifecyclesDefined {
            get {
                return ResourceManager.GetString("msgNoLifecyclesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the permission to move the following items:.
        /// </summary>
        internal static string msgNoMovePermission {
            get {
                return ResourceManager.GetString("msgNoMovePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object with the specified ID was not found..
        /// </summary>
        internal static string msgNoObjectFound {
            get {
                return ResourceManager.GetString("msgNoObjectFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have the permission to read the following items:.
        /// </summary>
        internal static string msgNoReadPermission {
            get {
                return ResourceManager.GetString("msgNoReadPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following references in the content are no associated objects:.
        /// </summary>
        internal static string msgReferencesNotFound {
            get {
                return ResourceManager.GetString("msgReferencesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in &apos;{0}&apos;. Do you want to save them?.
        /// </summary>
        internal static string msgSaveUnsavedChanges {
            get {
                return ResourceManager.GetString("msgSaveUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relations between an object and itself are not allowed..
        /// </summary>
        internal static string msgSelfReferencesNotAllowed {
            get {
                return ResourceManager.GetString("msgSelfReferencesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search returned very many results ({0}). 
        ///Searching for all results can take several minutes. 
        ///Consider narrowing the search criteria.
        ///Do you want to show all results?.
        /// </summary>
        internal static string msgShowAllSearchResults {
            get {
                return ResourceManager.GetString("msgShowAllSearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection was successfully exported to {0}..
        /// </summary>
        internal static string msgSuccessfullyExported {
            get {
                return ResourceManager.GetString("msgSuccessfullyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove the selected relations?
        ///The change will be committed when you click the Save button..
        /// </summary>
        internal static string msgSureRemoveRelations {
            get {
                return ResourceManager.GetString("msgSureRemoveRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown file extension..
        /// </summary>
        internal static string msgUnknownFileExtension {
            get {
                return ResourceManager.GetString("msgUnknownFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains word containing.
        /// </summary>
        internal static string opContainedWordContains {
            get {
                return ResourceManager.GetString("opContainedWordContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains word ending with.
        /// </summary>
        internal static string opContainedWordEndsWith {
            get {
                return ResourceManager.GetString("opContainedWordEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains word beginning with.
        /// </summary>
        internal static string opContainedWordStartsWith {
            get {
                return ResourceManager.GetString("opContainedWordStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains word.
        /// </summary>
        internal static string opContainsWord {
            get {
                return ResourceManager.GetString("opContainsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is after.
        /// </summary>
        internal static string opIsAfter {
            get {
                return ResourceManager.GetString("opIsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is before.
        /// </summary>
        internal static string opIsBefore {
            get {
                return ResourceManager.GetString("opIsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is equal to.
        /// </summary>
        internal static string opIsEqual {
            get {
                return ResourceManager.GetString("opIsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is equal to or after.
        /// </summary>
        internal static string opIsEqualOrAfter {
            get {
                return ResourceManager.GetString("opIsEqualOrAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is equal to or before.
        /// </summary>
        internal static string opIsEqualOrBefore {
            get {
                return ResourceManager.GetString("opIsEqualOrBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than or equal.
        /// </summary>
        internal static string opIsEqualOrGreater {
            get {
                return ResourceManager.GetString("opIsEqualOrGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than or equal.
        /// </summary>
        internal static string opIsEqualOrLess {
            get {
                return ResourceManager.GetString("opIsEqualOrLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is false.
        /// </summary>
        internal static string opIsFalse {
            get {
                return ResourceManager.GetString("opIsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is greater than.
        /// </summary>
        internal static string opIsGreater {
            get {
                return ResourceManager.GetString("opIsGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is less than.
        /// </summary>
        internal static string opIsLess {
            get {
                return ResourceManager.GetString("opIsLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is true.
        /// </summary>
        internal static string opIsTrue {
            get {
                return ResourceManager.GetString("opIsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contains.
        /// </summary>
        internal static string opStringContains {
            get {
                return ResourceManager.GetString("opStringContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ends with.
        /// </summary>
        internal static string opStringEndsWith {
            get {
                return ResourceManager.GetString("opStringEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begins with.
        /// </summary>
        internal static string opStringStartsWith {
            get {
                return ResourceManager.GetString("opStringStartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create folder.
        /// </summary>
        internal static string permFolderCreateFolder {
            get {
                return ResourceManager.GetString("permFolderCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create object.
        /// </summary>
        internal static string permFolderCreateObject {
            get {
                return ResourceManager.GetString("permFolderCreateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write link target.
        /// </summary>
        internal static string permLinkTargetWrite {
            get {
                return ResourceManager.GetString("permLinkTargetWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write ACL.
        /// </summary>
        internal static string permNodeAclWrite {
            get {
                return ResourceManager.GetString("permNodeAclWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string permNodeBrowse {
            get {
                return ResourceManager.GetString("permNodeBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string permNodeDelete {
            get {
                return ResourceManager.GetString("permNodeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read MD.
        /// </summary>
        internal static string permNodeMetadataRead {
            get {
                return ResourceManager.GetString("permNodeMetadataRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write MD.
        /// </summary>
        internal static string permNodeMetadataWrite {
            get {
                return ResourceManager.GetString("permNodeMetadataWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string permNodeMove {
            get {
                return ResourceManager.GetString("permNodeMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write name.
        /// </summary>
        internal static string permNodeNameWrite {
            get {
                return ResourceManager.GetString("permNodeNameWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write owner.
        /// </summary>
        internal static string permNodeOwnerWrite {
            get {
                return ResourceManager.GetString("permNodeOwnerWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write summary.
        /// </summary>
        internal static string permNodeSummaryWrite {
            get {
                return ResourceManager.GetString("permNodeSummaryWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write type.
        /// </summary>
        internal static string permNodeTypeWrite {
            get {
                return ResourceManager.GetString("permNodeTypeWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read content.
        /// </summary>
        internal static string permObjectContentRead {
            get {
                return ResourceManager.GetString("permObjectContentRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write content.
        /// </summary>
        internal static string permObjectContentWrite {
            get {
                return ResourceManager.GetString("permObjectContentWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write language.
        /// </summary>
        internal static string permObjectLanguageWrite {
            get {
                return ResourceManager.GetString("permObjectLanguageWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write LC state.
        /// </summary>
        internal static string permObjectLifecycleStateWrite {
            get {
                return ResourceManager.GetString("permObjectLifecycleStateWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        internal static string permObjectLock {
            get {
                return ResourceManager.GetString("permObjectLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string permObjectVersion {
            get {
                return ResourceManager.GetString("permObjectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child.
        /// </summary>
        internal static string permRelationChildAdd {
            get {
                return ResourceManager.GetString("permRelationChildAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove child.
        /// </summary>
        internal static string permRelationChildRemove {
            get {
                return ResourceManager.GetString("permRelationChildRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add parent.
        /// </summary>
        internal static string permRelationParentAdd {
            get {
                return ResourceManager.GetString("permRelationParentAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove parent.
        /// </summary>
        internal static string permRelationParentRemove {
            get {
                return ResourceManager.GetString("permRelationParentRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents.
        /// </summary>
        internal static string tabShowFolderContents {
            get {
                return ResourceManager.GetString("tabShowFolderContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string ttSave {
            get {
                return ResourceManager.GetString("ttSave", resourceCulture);
            }
        }
    }
}
